### ISSUE TITLE
github release for readable semver dependency

### ISSUE THREAD

**Issue by akkumar** [yookoala/realpath#3]
I am using dep for dependency management. 

( While I could still use master branch directly for the same ) , it would be useful if a github release ( say, 0.0.1 or similar ) were made so the semver dependency could be more readable and maintainable.

**Comment by yookoala** [comment]
Just tagged the latest master as [v1.0.0](https://github.com/yookoala/realpath/tree/v1.0.0). Please see if it helps :-)

**Comment by akkumar** [comment]
Thanks a lot. This helps !

**Comment by akkumar** [comment]
```toml
[[constraint]]
  name = "github.com/yookoala/realpath"
  version = "1.0.0"
```

For those stumbling upon this - you can add the above to Gopkg.toml to set the right constraint and allow dep to consistently reproduce the same
